# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Symfony

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  symfony-tests:
    runs-on: ubuntu-latest
    steps:
      # Utilisation d'une version spécifique de shivammathur/setup-php
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      # Checkout du code source
      - uses: actions/checkout@v4

      # Copier le fichier .env.test.local s'il n'existe pas
      - name: Copy .env.test.local
        run: php -r "file_exists('.env.test.local') || copy('.env.test', '.env.test.local');"

      # Mise en cache des packages Composer
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      # Installation des dépendances via Composer
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      # Création de la base de données pour les tests
      - name: Create Database
        run: |
          mkdir -p data
          touch data/database.sqlite

      # Exécution des tests unitaires et fonctionnels avec PHPUnit
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DATABASE_URL: sqlite:///%kernel.project_dir%/data/database.sqlite
        run: vendor/bin/phpunit
      # Donner les permissions d'exécution pour le fichier Symfony console
      - name: Grant execute permissions for Symfony console
        run: chmod +x bin/console
        
      # Analyse statique du code avec PHPStan
      - name: Static analysis of PHP code (PHPStan)
        run: vendor/bin/phpstan analyse -l max -c configurations/.phpstan.neon --memory-limit 1G
